services:
  - type: web
    name: tiktok-automation
    env: node
    plan: starter
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: CHROME_BIN
        value: /usr/bin/google-chrome-stable
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/google-chrome-stable
    disk:
      name: data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
    port: 5000 # Ensure to add this
