
services:
  - type: web
    name: tiktok-automation
    env: node
    plan: starter
    buildCommand: chmod +x scripts/render-build.sh && ./scripts/render-build.sh
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: tiktok-automation-db
          property: connectionString
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true
    healthCheckPath: /api/health

databases:
  - name: tiktok-automation-db
    databaseName: tiktok_automation
    user: tiktok_user
    plan: starter
