services:
  - type: web
    name: tiktok-automation
    env: node
    plan: starter
    buildCommand: npm install --include=dev && npx puppeteer browsers install chrome && npx vite build && npx esbuild server/index.ts --platform=node --packages=external --bundle --format=esm --outdir=dist && node init-db.js
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: false
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/.cache/puppeteer
    disk:
      name: data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
    port: 5000 # Ensure to add this
